name: CI (Lint, Format, Test)

on:
  push:
    branches: [main, master, feature/**]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/checkout@v4
        with:
          node-version: "20" # Matches modern React 19 / Vite requirements
          cache: "npm"

      - name: Install dependencies
        # We use --legacy-peer-deps to handle the ESLint/React 19 conflicts we saw earlier
        run: npm install --legacy-peer-deps

      - name: Check Formatting (Prettier)
        # This assumes you have a "format:check" or "prettier" script in package.json
        run: npx prettier --check .

      - name: Lint (ESLint)
        run: npm run lint

      - name: Run Tests (Vitest)
        # We use 'run' mode for CI to ensure it exits after one execution
        run: npm run test:ci
